.TH "AESKeystore_info_st" 3 "9 Oct 2013" "Version 0.8.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AESKeystore_info_st \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ASN1_INTEGER * \fBversion\fP"
.br
.ti -1c
.RI "ASN1_OBJECT * \fBalgorithm_oid\fP"
.br
.ti -1c
.RI "ASN1_OCTET_STRING * \fBencrypted_key\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file aeskeystoreasn1.h.
.SH "Field Documentation"
.PP 
.SS "ASN1_OBJECT* \fBAESKeystore_info_st::algorithm_oid\fP"
.PP
Definition at line 29 of file aeskeystoreasn1.h.
.PP
Referenced by ccn_aes_keystore_file_init(), and ccn_aes_keystore_init().
.SS "ASN1_OCTET_STRING* \fBAESKeystore_info_st::encrypted_key\fP"
.PP
Definition at line 30 of file aeskeystoreasn1.h.
.PP
Referenced by ccn_aes_keystore_file_init(), and ccn_aes_keystore_init().
.SS "ASN1_INTEGER* \fBAESKeystore_info_st::version\fP"
.PP
Definition at line 28 of file aeskeystoreasn1.h.
.PP
Referenced by ccn_aes_keystore_file_init(), and ccn_aes_keystore_init().

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
