include/ccn/btree_content.h
NAME
include/ccn/btree_content.h -
Storage of a content index in a btree.
SYNOPSIS
Data Structures
struct ccn_btree_content_payload
Structure of the entry payload within a leaf node.
struct ccn_btree_content_entry
Logical structure of the entry within a leaf node.
Defines
#define CCN_BT_CONTENT_MAGIC 0xC0
#define CCN_RCFLAG_LASTBLOCK 0x80
#define CCN_RCFLAG_STALE 0x01
Functions
int ccn_btree_match_interest (struct ccn_btree_node *node, int ndx, const unsigned char *interest_msg, const struct ccn_parsed_interest *pi, struct ccn_charbuf *scratch)
Test for a match between the ContentObject described by a btree index entry and an Interest, assuming that it is already known that there is a prefix match.
int ccn_btree_insert_content (struct ccn_btree_node *node, int ndx, uint_least64_t cobid, const unsigned char *content_object, struct ccn_parsed_ContentObject *pc, struct ccn_charbuf *flatname)
Insert a ContentObject into a btree node.
uint_least64_t ccn_btree_content_cobid (struct ccn_btree_node *node, int ndx)
Get cobid from btree entry.
int ccn_btree_content_set_cobid (struct ccn_btree_node *node, int ndx, uint_least64_t cobid)
Set cobid in a btree entry.
int ccn_btree_content_cobsz (struct ccn_btree_node *node, int ndx)
Get ContentObject size from btree entry.
Detailed Description
Storage of a content index in a btree.
Definition in file btree_content.h.
Define Documentation
#define CCN_BT_CONTENT_MAGIC 0xC0
Definition at line 45 of file btree_content.h.
Referenced by ccn_btree_insert_content(), and ccn_btree_match_interest().
#define CCN_RCFLAG_LASTBLOCK 0x80
Definition at line 46 of file btree_content.h.
#define CCN_RCFLAG_STALE 0x01
Definition at line 47 of file btree_content.h.
Function Documentation
uint_least64_t ccn_btree_content_cobid (struct ccn_btree_node * node, int ndx)
Get cobid from btree entry. Returns:
the cobid field of the indexed entry of node, or 0 if error.
Definition at line 226 of file ccn_btree_content.c.
Referenced by r_store_content_btree_insert(), and r_store_look().
int ccn_btree_content_cobsz (struct ccn_btree_node * node, int ndx)
Get ContentObject size from btree entry. Returns:
the cobsz field of the indexed entry of node, or -1 if error.
Definition at line 265 of file ccn_btree_content.c.
Referenced by r_store_look().
int ccn_btree_content_set_cobid (struct ccn_btree_node * node, int ndx, uint_least64_t cobid)
Set cobid in a btree entry. Returns:
0 for success, -1 for failure
Definition at line 243 of file ccn_btree_content.c.
Referenced by r_store_set_accession_from_offset().
int ccn_btree_insert_content (struct ccn_btree_node * node, int ndx, uint_least64_t cobid, const unsigned char * content_object, struct ccn_parsed_ContentObject * pc, struct ccn_charbuf * flatname)
Insert a ContentObject into a btree node. The caller has presumably already done a lookup and found that the object is not there.
The caller is responsible for provinding a valid content parse (pc).
The flatname buffer should hold the correct full name, including the digest.
Returns:
the new entry count or, -1 for error.
Definition at line 75 of file ccn_btree_content.c.
Referenced by r_store_content_btree_insert(), and test_insert_content().
int ccn_btree_match_interest (struct ccn_btree_node * node, int ndx, const unsigned char * interest_msg, const struct ccn_parsed_interest * pi, struct ccn_charbuf * scratch)
Test for a match between the ContentObject described by a btree index entry and an Interest, assuming that it is already known that there is a prefix match. This does not need access to the actual ContentObject, since the index entry contains everything that we know to know to do the match.
Parameters:
node leaf node
ndx index of entry within leaf node
interest_msg ccnb-encoded Interest
pi corresponding parsed interest
scratch for scratch use
Returns:
1 for match, 0 for no match, -1 for error.
Definition at line 142 of file ccn_btree_content.c.
Referenced by r_store_lookup(), r_store_lookup_backwards(), r_sync_enumerate_action(), and testhelp_count_matches().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.