lib/ccn_buf_encoder.c
NAME
lib/ccn_buf_encoder.c -
Support for constructing various ccnb-encoded objects.
SYNOPSIS
Functions
int ccn_signed_info_create (struct ccn_charbuf *c, const void *publisher_key_id, size_t publisher_key_id_size, const struct ccn_charbuf *timestamp, enum ccn_content_type type, int freshness, const struct ccn_charbuf *finalblockid, const struct ccn_charbuf *key_locator)
Create SignedInfo.
static int ccn_encode_Signature (struct ccn_charbuf *buf, const char *digest_algorithm, const void *witness, size_t witness_size, const struct ccn_signature *signature, size_t signature_size)
int ccn_encode_ContentObject (struct ccn_charbuf *buf, const struct ccn_charbuf *Name, const struct ccn_charbuf *SignedInfo, const void *data, size_t size, const char *digest_algorithm, const struct ccn_pkey *key)
Encode and sign a ContentObject.
int ccn_encode_StatusResponse (struct ccn_charbuf *buf, int errcode, const char *errtext)
int ccn_charbuf_append_tt (struct ccn_charbuf *c, size_t val, enum ccn_tt tt)
Append a ccnb start marker.
int ccn_charbuf_append_closer (struct ccn_charbuf *c)
Append a CCN_CLOSE.
int ccnb_append_number (struct ccn_charbuf *c, int nni)
Append a non-negative integer as a UDATA.
int ccnb_append_timestamp_blob (struct ccn_charbuf *c, enum ccn_marker marker, intmax_t secs, int nsecs)
Append a binary timestamp as a BLOB using the ccn binary Timestamp representation (12-bit fraction).
int ccnb_append_now_blob (struct ccn_charbuf *c, enum ccn_marker marker)
Append a binary timestamp, using the current time.
int ccnb_element_begin (struct ccn_charbuf *c, enum ccn_dtag dtag)
Append a start-of-element marker.
int ccnb_element_end (struct ccn_charbuf *c)
Append an end-of-element marker.
int ccnb_append_tagged_blob (struct ccn_charbuf *c, enum ccn_dtag dtag, const void *data, size_t size)
Append a tagged BLOB.
int ccnb_append_tagged_binary_number (struct ccn_charbuf *cb, enum ccn_dtag dtag, uintmax_t val)
Append a tagged binary number as a blob containing the integer value.
int ccnb_append_tagged_udata (struct ccn_charbuf *c, enum ccn_dtag dtag, const void *data, size_t size)
Append a tagged UDATA string.
int ccnb_tagged_putf (struct ccn_charbuf *c, enum ccn_dtag dtag, const char *fmt,...)
Append a tagged UDATA string, with printf-style formatting.
int ccnb_append_Link (struct ccn_charbuf *buf, const struct ccn_charbuf *name, const char *label, const struct ccn_charbuf *linkAuthenticator)
Append a representation of a Link to a charbuf.
Detailed Description
Support for constructing various ccnb-encoded objects.
Part of the CCNx C Library.
Copyright (C) 2008-2013 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file ccn_buf_encoder.c.
Function Documentation
int ccn_charbuf_append_closer (struct ccn_charbuf * c)
Append a CCN_CLOSE. Use this to close off an element in ccnb-encoded data.
Parameters:
c is the buffer to append to.
Returns:
0 for success or -1 for error.
Definition at line 284 of file ccn_buf_encoder.c.
Referenced by ccn_name_from_uri(), ccnb_element_end(), and me_too().
int ccn_charbuf_append_tt (struct ccn_charbuf * c, size_t val, enum ccn_tt tt)
Append a ccnb start marker. This forms the basic building block of ccnb-encoded data.
Parameters:
c is the buffer to append to.
val is the numval, intepreted according to tt (see enum ccn_tt).
tt is the type field.
Returns:
0 for success or -1 for error.
Definition at line 266 of file ccn_buf_encoder.c.
Referenced by append_bloom_element(), ccn_append_link_stuff(), ccn_append_pubkey_blob(), ccn_encode_ContentObject(), ccn_sign_content(), ccn_signed_info_create(), ccnb_append_number(), ccnb_append_tagged_blob(), ccnb_append_tagged_udata(), ccnb_append_timestamp_blob(), ccnb_element_begin(), ccnb_tagged_putf(), and SyncAppendRandomHash().
int ccn_encode_ContentObject (struct ccn_charbuf * buf, const struct ccn_charbuf * Name, const struct ccn_charbuf * SignedInfo, const void * data, size_t size, const char * digest_algorithm, const struct ccn_pkey * key)
Encode and sign a ContentObject. Parameters:
buf is the output buffer where encoded object is written.
Name is the ccnb-encoded name from ccn_name_init and friends.
SignedInfo is the ccnb-encoded info from ccn_signed_info_create.
data pintes to the raw data to be encoded.
size is the size, in bytes, of the raw data to be encoded.
digest_algorithm may be NULL for default.
key is the private or symmetric key to use for signing.
Returns:
0 for success or -1 for error.
Definition at line 150 of file ccn_buf_encoder.c.
Referenced by ccn_sign_content(), encode_message(), and main().
static int ccn_encode_Signature (struct ccn_charbuf * buf, const char * digest_algorithm, const void * witness, size_t witness_size, const struct ccn_signature * signature, size_t signature_size) [static]
Definition at line 108 of file ccn_buf_encoder.c.
Referenced by ccn_encode_ContentObject().
int ccn_encode_StatusResponse (struct ccn_charbuf * buf, int errcode, const char * errtext)
Definition at line 242 of file ccn_buf_encoder.c.
Referenced by ccnd_nack().
int ccn_signed_info_create (struct ccn_charbuf * c, const void * publisher_key_id, size_t publisher_key_id_size, const struct ccn_charbuf * timestamp, enum ccn_content_type type, int freshness, const struct ccn_charbuf * finalblockid, const struct ccn_charbuf * key_locator)
Create SignedInfo. Parameters:
c is used to hold the result.
publisher_key_id points to the digest of the publisher key id.
publisher_key_id_size is the size in bytes(32) of the pub key digest
timestamp holds the timestamp, as a ccnb-encoded blob, or is NULL to use the current time.
type indicates the Type of the ContentObject.
freshness is the FreshnessSeconds value, or -1 to omit.
finalblockid holds the FinalBlockID, as a ccnb-encoded blob, or is NULL to omit.
key_locator is the ccnb-encoded KeyLocator element, or NULL to omit.
Returns:
0 for success or -1 for error.
Definition at line 49 of file ccn_buf_encoder.c.
Referenced by ccn_sign_content(), and main().
int ccnb_append_Link (struct ccn_charbuf * buf, const struct ccn_charbuf * name, const char * label, const struct ccn_charbuf * linkAuthenticator)
Append a representation of a Link to a charbuf. Parameters:
buf is the output buffer where encoded link is written.
name is the ccnb-encoded name from ccn_name_init and friends.
label is a UTF-8 string in a ccn_charbuf.
linkAuthenticator is the ccnb-encoded LinkAuthenticator.
Returns:
0 for success or -1 for error.
Definition at line 534 of file ccn_buf_encoder.c.
Referenced by ccnr_init_policy_link_cob(), and main().
int ccnb_append_now_blob (struct ccn_charbuf * c, enum ccn_marker marker)
Append a binary timestamp, using the current time. Like ccnb_append_timestamp_blob() but uses current time
Parameters:
c is the buffer to append to.
marker - see ccnb_append_timestamp_blob()
Returns:
0 for success or -1 for error.
Definition at line 368 of file ccn_buf_encoder.c.
Referenced by ccn_create_version(), and ccn_signed_info_create().
int ccnb_append_number (struct ccn_charbuf * c, int nni)
Append a non-negative integer as a UDATA. Parameters:
c is the buffer to append to.
nni is a non-negative value.
Returns:
0 for success or -1 for error.
Definition at line 299 of file ccn_buf_encoder.c.
Referenced by main(), make_data_template(), and make_template().
int ccnb_append_tagged_binary_number (struct ccn_charbuf * cb, enum ccn_dtag dtag, uintmax_t val)
Append a tagged binary number as a blob containing the integer value. This is a ccnb-encoded element holding a
Parameters:
cb is the buffer to append to.
dtag is the element's dtab
val is the unsigned integer to be appended
Returns:
0 for success or -1 for error.
Definition at line 433 of file ccn_buf_encoder.c.
Referenced by make_ra_template(), resolve_templ(), and send_interest().
int ccnb_append_tagged_blob (struct ccn_charbuf * c, enum ccn_dtag dtag, const void * data, size_t size)
Append a tagged BLOB. This is a ccnb-encoded element with containing the BLOB as content
Parameters:
c is the buffer to append to.
dtag is the element's dtab
data points to the binary data
size is the size of the data, in bytes
Returns:
0 for success or -1 for error.
Definition at line 408 of file ccn_buf_encoder.c.
Referenced by append_bf_all(), append_future_vcomp(), appendExclusions(), appendLifetime(), ccn_encode_ContentObject(), ccn_encode_Signature(), ccn_name_append(), ccn_signed_info_create(), ccnb_append_face_instance(), ccnb_append_forwarding_entry(), ccnb_append_header(), ccnb_append_tagged_binary_number(), ccnd_adjacency_offer_or_commit_req(), main(), make_ra_template(), putFile(), resolve_templ(), send_adjacency_solicit(), send_interest(), SyncAppendElementInner(), and SyncNodeAppendLongHash().
int ccnb_append_tagged_udata (struct ccn_charbuf * c, enum ccn_dtag dtag, const void * data, size_t size)
Append a tagged UDATA string. This is a ccnb-encoded element containing the UDATA as content
Parameters:
c is the buffer to append to.
dtag is the element's dtab
data points to the data
size is the size of the data, in bytes
Returns:
0 for success or -1 for error.
Definition at line 456 of file ccn_buf_encoder.c.
Referenced by answer_passive(), ccn_encode_Signature(), ccnb_append_Link(), incoming_content(), and local_scope().
int ccnb_append_timestamp_blob (struct ccn_charbuf * c, enum ccn_marker marker, intmax_t secs, int nsecs)
Append a binary timestamp as a BLOB using the ccn binary Timestamp representation (12-bit fraction). Parameters:
c is the buffer to append to.
marker If marker >= 0, the low-order byte is used as a marker byte, useful for some content naming conventions (versioning, in particular).
secs - seconds since epoch
nsecs - nanoseconds
Returns:
0 for success or -1 for error.
Definition at line 327 of file ccn_buf_encoder.c.
Referenced by ccn_create_version(), ccnb_append_now_blob(), and main().
int ccnb_element_begin (struct ccn_charbuf * c, enum ccn_dtag dtag)
Append a start-of-element marker.
Definition at line 382 of file ccn_buf_encoder.c.
Referenced by append_Any_filter(), append_bloom_element(), append_filter_all(), append_slice(), appendExclusions(), ccn_append_link_stuff(), ccn_construct_interest(), ccn_create_version(), ccn_encode_ContentObject(), ccn_encode_Signature(), ccn_encode_StatusResponse(), ccn_guest_prefix(), ccn_initiate_key_fetch(), ccn_name_init(), ccn_sign_content(), ccn_signed_info_create(), ccnb_append_face_instance(), ccnb_append_forwarding_entry(), ccnb_append_header(), ccnb_append_Link(), ccnb_append_tagged_blob(), ccnb_append_tagged_udata(), ccnb_tagged_putf(), ccnd_adjacency_offer_or_commit_req(), ccnd_init_service_ccnb(), ccndc_initialize_data(), ccnr_init_service_ccnb(), create_passive_templ(), express_bulkdata_interest(), express_interest(), express_my_interest(), handle_key(), incoming_content(), local_scope_rm_template(), main(), make_data_template(), make_ra_template(), make_scope1_template(), make_template(), NewDeltas(), putFile(), r_proto_append_repo_info(), r_proto_begin_enumeration(), r_proto_continue_enumeration(), r_proto_initiate_key_fetch(), r_proto_mktemplate(), r_proto_policy_append_basic(), r_proto_start_write_checked(), resolve_templ(), send_adjacency_solicit(), sendSlice(), stuff_and_send(), stuff_link_check(), SyncAppendElementInner(), SyncAppendRandomHash(), SyncAppendRandomName(), SyncGenInterest(), SyncResetComposite(), SyncRootAppendSlice(), SyncSignBuf(), and testEncodeDecode().
int ccnb_element_end (struct ccn_charbuf * c)
Append an end-of-element marker. This is the same as ccn_charbuf_append_closer()
Definition at line 392 of file ccn_buf_encoder.c.
Referenced by append_Any_filter(), append_bloom_element(), append_filter_all(), append_slice(), appendExclusions(), ccn_append_link_stuff(), ccn_construct_interest(), ccn_create_version(), ccn_encode_ContentObject(), ccn_encode_Signature(), ccn_encode_StatusResponse(), ccn_guest_prefix(), ccn_initiate_key_fetch(), ccn_name_append(), ccn_name_append_components(), ccn_name_init(), ccn_sign_content(), ccn_signed_info_create(), ccnb_append_face_instance(), ccnb_append_forwarding_entry(), ccnb_append_header(), ccnb_append_Link(), ccnb_append_tagged_blob(), ccnb_append_tagged_udata(), ccnb_tagged_putf(), ccnd_adjacency_offer_or_commit_req(), ccnd_answer_req(), ccnd_init_service_ccnb(), ccnd_req_guest(), ccndc_initialize_data(), ccnr_init_service_ccnb(), CloseUpdateCoding(), create_passive_templ(), express_bulkdata_interest(), express_interest(), express_my_interest(), handle_key(), incoming_content(), local_scope_rm_template(), main(), make_data_template(), make_ra_template(), make_scope1_template(), make_template(), putFile(), r_proto_append_repo_info(), r_proto_begin_enumeration(), r_proto_continue_enumeration(), r_proto_initiate_key_fetch(), r_proto_mktemplate(), r_proto_policy_append_basic(), r_proto_policy_append_namespace(), r_proto_start_write(), r_proto_start_write_checked(), resolve_templ(), send_adjacency_solicit(), send_interest(), sendSlice(), stuff_and_send(), stuff_link_check(), SyncAppendElementInner(), SyncAppendRandomHash(), SyncAppendRandomName(), SyncEndComposite(), SyncGenInterest(), SyncRootAppendSlice(), SyncSignBuf(), and testEncodeDecode().
int ccnb_tagged_putf (struct ccn_charbuf * c, enum ccn_dtag dtag, const char * fmt, ...)
Append a tagged UDATA string, with printf-style formatting. This is a ccnb-encoded element containing UDATA as content.
Parameters:
c is the buffer to append to.
dtag is the element's dtab.
fmt is a printf-style format string, followed by its values
Returns:
0 for success or -1 for error.
Definition at line 482 of file ccn_buf_encoder.c.
Referenced by answer_highest(), answer_passive(), append_slice(), ccn_encode_StatusResponse(), ccn_guest_prefix(), ccn_initiate_key_fetch(), ccn_signed_info_create(), ccnb_append_face_instance(), ccnb_append_forwarding_entry(), ccnb_append_header(), ccnd_adjacency_offer_or_commit_req(), ccndc_initialize_data(), express_interest(), handle_key(), incoming_content(), local_scope_rm_template(), main(), make_ra_template(), make_scope1_template(), make_template(), me_too(), r_proto_append_repo_info(), r_proto_initiate_key_fetch(), r_proto_mktemplate(), r_proto_policy_append_basic(), r_proto_policy_append_namespace(), resolve_templ(), send_adjacency_solicit(), stuff_link_check(), SyncAppendTaggedNumber(), SyncGenInterest(), and SyncSignBuf().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.