.TH "lib/ccn_aes_keystore_asn1.c" 3 "9 Oct 2013" "Version 0.8.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/ccn_aes_keystore_asn1.c \- 
.PP
Framework to generate implementation of ASN.1 functions to deal with AES keystores.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Framework to generate implementation of ASN.1 functions to deal with AES keystores. 

Part of the CCNx C Library.
.PP
Copyright (C) 2013 Palo Alto Research Center, Inc.
.PP
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 
.PP
Definition in file \fBccn_aes_keystore_asn1.c\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
