lib/ccn_aes_keystore.c
NAME
lib/ccn_aes_keystore.c -
Support for aes (symmetric) keystore access.
SYNOPSIS
Defines
#define AES_KEYSTORE_VERSION 1L
#define IV_SIZE 16
#define AES_MAX_DIGEST_SIZE 128
Functions
static unsigned char * create_derived_key (const char *key, unsigned int keylength, unsigned char *salt, unsigned int saltlen)
static ssize_t ccn_aes_keystore_key_digest_length (struct ccn_keystore *p)
static const unsigned char * ccn_aes_keystore_key_digest (struct ccn_keystore *p)
static struct ccn_pkey * get_key_from_aes_keystore (struct ccn_keystore *ks)
static const char * ccn_aes_keystore_digest_algorithm (struct ccn_keystore *p)
static void ccn_aes_keystore_destroy (struct ccn_keystore **p)
struct ccn_keystore * ccn_aes_keystore_create (void)
static int ccn_aes_digest (unsigned char *key, unsigned int keylength, unsigned char *key_digest)
int ccn_aes_keystore_init (struct ccn_keystore *keystore, char *filename, const char *password)
int ccn_aes_keystore_file_init (char *filename, const char *password, unsigned char *key, int keylength)
Create an AES keystore file.
void ccn_generate_symmetric_key (unsigned char *keybuf, int keylength)
int ccn_create_aes_filename_from_key (struct ccn_charbuf *filename, unsigned char *key, int keylength)
void ccn_create_filename_with_digest_suffix (struct ccn_charbuf *filename, const unsigned char *digest, int digest_len)
Detailed Description
Support for aes (symmetric) keystore access.
Part of the CCNx C Library.
Copyright (C) 2013 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file ccn_aes_keystore.c.
Define Documentation
#define AES_KEYSTORE_VERSION 1L
Definition at line 41 of file ccn_aes_keystore.c.
Referenced by ccn_aes_keystore_file_init(), and ccn_aes_keystore_init().
#define AES_MAX_DIGEST_SIZE 128
Definition at line 43 of file ccn_aes_keystore.c.
#define IV_SIZE 16
Definition at line 42 of file ccn_aes_keystore.c.
Referenced by ccn_aes_keystore_file_init(), and ccn_aes_keystore_init().
Function Documentation
static int ccn_aes_digest (unsigned char * key, unsigned int keylength, unsigned char * key_digest) [static]
Definition at line 102 of file ccn_aes_keystore.c.
Referenced by ccn_aes_keystore_init(), and ccn_create_aes_filename_from_key().
struct ccn_keystore* ccn_aes_keystore_create (void) [read]
Definition at line 90 of file ccn_aes_keystore.c.
Referenced by ccn_load_signing_key(), ccn_locate_key(), and main().
static void ccn_aes_keystore_destroy (struct ccn_keystore ** p) [static]
Definition at line 81 of file ccn_aes_keystore.c.
Referenced by ccn_aes_keystore_create().
static const char* ccn_aes_keystore_digest_algorithm (struct ccn_keystore * p) [static]
Definition at line 75 of file ccn_aes_keystore.c.
Referenced by ccn_aes_keystore_create().
int ccn_aes_keystore_file_init (char * filename, const char * password, unsigned char * key, int keylength)
Create an AES keystore file. Parameters:
filename the name of the keystore file to be created.
password the import/export password for the keystore.
key the key to encrypt in the keystore
Returns:
0 on success, -1 on failure
Definition at line 203 of file ccn_aes_keystore.c.
Referenced by main().
int ccn_aes_keystore_init (struct ccn_keystore * keystore, char * filename, const char * password)
Definition at line 117 of file ccn_aes_keystore.c.
Referenced by ccn_load_signing_key(), ccn_locate_key(), and main().
static const unsigned char* ccn_aes_keystore_key_digest (struct ccn_keystore * p) [static]
Definition at line 63 of file ccn_aes_keystore.c.
Referenced by ccn_aes_keystore_create().
static ssize_t ccn_aes_keystore_key_digest_length (struct ccn_keystore * p) [static]
Definition at line 57 of file ccn_aes_keystore.c.
Referenced by ccn_aes_keystore_create().
int ccn_create_aes_filename_from_key (struct ccn_charbuf * filename, unsigned char * key, int keylength)
Definition at line 293 of file ccn_aes_keystore.c.
Referenced by main().
void ccn_create_filename_with_digest_suffix (struct ccn_charbuf * filename, const unsigned char * digest, int digest_len)
Definition at line 306 of file ccn_aes_keystore.c.
Referenced by ccn_create_aes_filename_from_key(), and ccn_locate_key().
void ccn_generate_symmetric_key (unsigned char * keybuf, int keylength)
Definition at line 283 of file ccn_aes_keystore.c.
Referenced by main().
static unsigned char * create_derived_key (const char * key, unsigned int keylength, unsigned char * salt, unsigned int saltlen) [static]
Definition at line 317 of file ccn_aes_keystore.c.
Referenced by ccn_aes_keystore_file_init(), and ccn_aes_keystore_init().
static struct ccn_pkey* get_key_from_aes_keystore (struct ccn_keystore * ks) [static, read]
Definition at line 69 of file ccn_aes_keystore.c.
Referenced by ccn_aes_keystore_create().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.