lib/ccn_nametree.c
NAME
lib/ccn_nametree.c -
SYNOPSIS
Defines
#define CCN_NAMETREE_IMPL
#define CCN_SKIPLIST_MAX_DEPTH 16
#define NAMETREE_PVT_PAYLOAD_OWNED 0x40
Functions
struct ccn_nametree * ccn_nametree_create (int initial_limit)
Create a new, empty nametree.
struct ccny * ccny_create (unsigned randombits, size_t payload_size)
Create a new nametree entry, not hooked up to anything.
int ccny_set_key (struct ccny *y, const unsigned char *key, size_t size)
Set the key in a nametree entry.
void ccny_set_key_fields (struct ccny *y, unsigned char *key, unsigned size)
Directly assign the key and keylen in a nametree entry.
struct ccny * ccny_from_cookie (struct ccn_nametree *h, ccn_cookie cookie)
Look up an entry, given a cookie.
static int ccny_skiplist_findbefore (struct ccn_nametree *h, const unsigned char *key, size_t size, struct ccny **ans)
Find the entry, or the one just before where it would go.
struct ccny * ccn_nametree_look_lt (struct ccn_nametree *h, const unsigned char *key, size_t size)
Look for an entry with a key less than the given key.
struct ccny * ccn_nametree_look_le (struct ccn_nametree *h, const unsigned char *key, size_t size)
Look for an entry with a key less than or equal to the given key.
struct ccny * ccn_nametree_lookup (struct ccn_nametree *h, const unsigned char *key, size_t size)
Look for an entry with a key equal to given key.
struct ccny * ccn_nametree_look_ge (struct ccn_nametree *h, const unsigned char *key, size_t size)
Look for an entry with a key greater than or equal to the given key.
struct ccny * ccn_nametree_look_gt (struct ccn_nametree *h, const unsigned char *key, size_t size)
Look for an entry with a key greater than the given key.
static ccn_cookie ccny_skiplist_insert (struct ccn_nametree *h, struct ccny *y)
Insert an entry into the skiplist.
static void ccny_skiplist_remove (struct ccn_nametree *h, struct ccny *y)
Remove an entry from the skiplist.
ccn_cookie ccny_enroll (struct ccn_nametree *h, struct ccny *y)
Enroll an entry into the nametree.
int ccn_nametree_grow (struct ccn_nametree *h)
Double the size of the direct lookup table.
void ccny_remove (struct ccn_nametree *h, struct ccny *y)
Remove y from the nametree.
void ccny_destroy (struct ccn_nametree *h, struct ccny **py)
Destroy a nametree entry.
void ccn_nametree_destroy (struct ccn_nametree **ph)
Destroy a nametree, deleting all entries.
void ccn_nametree_check (struct ccn_nametree *h)
Check the nametree for consistency.
int ccn_nametree_n (struct ccn_nametree *h)
Access the number of entries.
int ccn_nametree_limit (struct ccn_nametree *h)
Access the current limit on the number of entries.
ccn_cookie ccny_cookie (struct ccny *y)
Access the cookie.
void * ccny_payload (struct ccny *y)
Access the payload.
void ccny_set_payload (struct ccny *y, void *payload)
Set the payload.
const unsigned char * ccny_key (struct ccny *y)
Access the key.
unsigned ccny_keylen (struct ccny *y)
Access the key size.
unsigned ccny_info (struct ccny *y)
Get the client info.
void ccny_set_info (struct ccny *y, unsigned info)
Set the client info.
struct ccny * ccn_nametree_first (struct ccn_nametree *h)
Get the first entry.
struct ccny * ccny_next (struct ccny *y)
Get the next entry.
struct ccny * ccny_prev (struct ccny *y)
Get the previous entry.
struct ccny * ccn_nametree_last (struct ccn_nametree *h)
Get the last entry.
Detailed Description
Definition in file ccn_nametree.c.
Define Documentation
#define CCN_NAMETREE_IMPL
Definition at line 24 of file ccn_nametree.c.
#define CCN_SKIPLIST_MAX_DEPTH 16
Definition at line 27 of file ccn_nametree.c.
Referenced by ccn_nametree_create(), ccn_nametree_look_ge(), ccn_nametree_look_gt(), ccn_nametree_look_le(), ccn_nametree_look_lt(), ccn_nametree_lookup(), ccny_skiplist_insert(), and ccny_skiplist_remove().
#define NAMETREE_PVT_PAYLOAD_OWNED 0x40
Definition at line 28 of file ccn_nametree.c.
Referenced by ccny_create().
Function Documentation
void ccn_nametree_check (struct ccn_nametree * h)
Check the nametree for consistency.
Definition at line 526 of file ccn_nametree.c.
Referenced by test_inserts_from_stdin().
struct ccn_nametree* ccn_nametree_create (int initial_limit) [read]
Create a new, empty nametree. The initial_limit is the number of entries that may be inserted before growing the table.
Definition at line 37 of file ccn_nametree.c.
Referenced by ccnd_create(), and test_inserts_from_stdin().
void ccn_nametree_destroy (struct ccn_nametree ** ph)
Destroy a nametree, deleting all entries.
Definition at line 504 of file ccn_nametree.c.
Referenced by ccnd_destroy(), and test_inserts_from_stdin().
struct ccny* ccn_nametree_first (struct ccn_nametree * h) [read]
Get the first entry.
Definition at line 648 of file ccn_nametree.c.
Referenced by test_inserts_from_stdin().
int ccn_nametree_grow (struct ccn_nametree * h)
Double the size of the direct lookup table. Returns:
0 for success, -1 for error.
Definition at line 433 of file ccn_nametree.c.
Referenced by process_incoming_content(), test_inserts_from_stdin(), and update_ex_index().
struct ccny* ccn_nametree_last (struct ccn_nametree * h) [read]
Get the last entry.
Definition at line 669 of file ccn_nametree.c.
Referenced by test_inserts_from_stdin().
int ccn_nametree_limit (struct ccn_nametree * h)
Access the current limit on the number of entries.
Definition at line 589 of file ccn_nametree.c.
struct ccny* ccn_nametree_look_ge (struct ccn_nametree * h, const unsigned char * key, size_t size) [read]
Look for an entry with a key greater than or equal to the given key. When there are multiple possibilities, the one with the smallest key is returned. Returns NULL if nothing matches.
Definition at line 278 of file ccn_nametree.c.
Referenced by ccn_nametree_check(), find_first_match_candidate(), and next_child_at_level().
struct ccny* ccn_nametree_look_gt (struct ccn_nametree * h, const unsigned char * key, size_t size) [read]
Look for an entry with a key greater than the given key. When there are multiple possibilities, the one with the smallest key is returned. Returns NULL if nothing matches.
Definition at line 294 of file ccn_nametree.c.
Referenced by ccn_nametree_check().
struct ccny* ccn_nametree_look_le (struct ccn_nametree * h, const unsigned char * key, size_t size) [read]
Look for an entry with a key less than or equal to the given key. When there are multiple possibilities, the one with the largest key is returned. Returns NULL if nothing matches.
Definition at line 241 of file ccn_nametree.c.
Referenced by ccn_nametree_check(), and content_enqueuex().
struct ccny* ccn_nametree_look_lt (struct ccn_nametree * h, const unsigned char * key, size_t size) [read]
Look for an entry with a key less than the given key. When there are multiple possibilities, the one with the largest key is returned. Returns NULL if nothing matches.
Definition at line 223 of file ccn_nametree.c.
Referenced by ccn_nametree_check().
struct ccny* ccn_nametree_lookup (struct ccn_nametree * h, const unsigned char * key, size_t size) [read]
Look for an entry with a key equal to given key.
Definition at line 259 of file ccn_nametree.c.
Referenced by test_inserts_from_stdin(), and update_ex_index().
int ccn_nametree_n (struct ccn_nametree * h)
Access the number of entries.
Definition at line 582 of file ccn_nametree.c.
ccn_cookie ccny_cookie (struct ccny * y)
Access the cookie.
Definition at line 596 of file ccn_nametree.c.
Referenced by process_incoming_content(), test_inserts_from_stdin(), and update_ex_index().
struct ccny* ccny_create (unsigned randombits, size_t payload_size) [read]
Create a new nametree entry, not hooked up to anything. The skiplinks array needs to be sized with an appropriate random distribution; for this purpose the caller must provide a word of random bits.
If payload_size is non-zero, extra zero-initialized space will be allocated, and a pointer to it provided in the payload field. This will be automatically freed when the entry is destroyed.
If the payload size is zero, the caller assumes resonsibility for managing the payload memory, probably by providing a suitable finalize action.
Definition at line 91 of file ccn_nametree.c.
Referenced by ccn_nametree_create(), process_incoming_content(), test_inserts_from_stdin(), and update_ex_index().
void ccny_destroy (struct ccn_nametree * h, struct ccny ** py)
Destroy a nametree entry. The entry must not be in any nametree.
Definition at line 486 of file ccn_nametree.c.
Referenced by ccn_nametree_destroy(), process_incoming_content(), remove_content(), test_inserts_from_stdin(), and update_ex_index().
ccn_cookie ccny_enroll (struct ccn_nametree * h, struct ccny * y)
Enroll an entry into the nametree. Although this detects a full table, caller should prevent that from ever happening by trimming or resizing as appropriate, to maintain some percentage of free slots.
Returns:
cookie of old entry in the case that one with the old key is present, or 0 upon success or a full table. The latter case may be disambiguated by examining y->cookie.
Definition at line 395 of file ccn_nametree.c.
Referenced by process_incoming_content(), test_inserts_from_stdin(), and update_ex_index().
struct ccny* ccny_from_cookie (struct ccn_nametree * h, ccn_cookie cookie) [read]
Look up an entry, given a cookie.
Definition at line 168 of file ccn_nametree.c.
Referenced by ccn_nametree_check(), ccnd_debug_content(), content_from_accession(), content_matches_prefix(), content_next(), match_interests(), next_child_at_level(), process_incoming_content(), and remove_content().
unsigned ccny_info (struct ccny * y)
Get the client info.
Definition at line 634 of file ccn_nametree.c.
Referenced by content_enqueuex().
const unsigned char* ccny_key (struct ccny * y)
Access the key.
Definition at line 620 of file ccn_nametree.c.
Referenced by ccnd_debug_content(), content_matches_prefix(), match_interests(), and next_child_at_level().
unsigned ccny_keylen (struct ccny * y)
Access the key size.
Definition at line 627 of file ccn_nametree.c.
Referenced by ccnd_debug_content(), content_matches_prefix(), match_interests(), and next_child_at_level().
struct ccny* ccny_next (struct ccny * y) [read]
Get the next entry.
Definition at line 655 of file ccn_nametree.c.
Referenced by content_next(), and test_inserts_from_stdin().
void* ccny_payload (struct ccny * y)
Access the payload.
Definition at line 605 of file ccn_nametree.c.
Referenced by content_finalize(), content_from_accession(), content_next(), content_preremove(), find_first_match_candidate(), next_child_at_level(), and process_incoming_content().
struct ccny* ccny_prev (struct ccny * y) [read]
Get the previous entry.
Definition at line 662 of file ccn_nametree.c.
Referenced by test_inserts_from_stdin().
void ccny_remove (struct ccn_nametree * h, struct ccny * y)
Remove y from the nametree. If y is not in the nametree, nothing is changed. On success, y->cookie is cleared, but y is not freed.
Definition at line 461 of file ccn_nametree.c.
Referenced by ccn_nametree_destroy(), remove_content(), test_inserts_from_stdin(), and update_ex_index().
void ccny_set_info (struct ccny * y, unsigned info)
Set the client info.
Definition at line 641 of file ccn_nametree.c.
Referenced by update_ex_index().
int ccny_set_key (struct ccny * y, const unsigned char * key, size_t size)
Set the key in a nametree entry. This makes a copy. The entry must not be in a nametree. Any old key is freed before making the copy.
A client may choose to manage the key storage differently, but in such a case it must provide a finalize action that leaves y->key NULL.
Returns:
-1 for error, 0 for success.
Definition at line 130 of file ccn_nametree.c.
Referenced by process_incoming_content(), and test_inserts_from_stdin().
void ccny_set_key_fields (struct ccny * y, unsigned char * key, unsigned size)
Directly assign the key and keylen in a nametree entry. This is for clients that are handling their own memory management.
Definition at line 158 of file ccn_nametree.c.
Referenced by update_ex_index().
void ccny_set_payload (struct ccny * y, void * payload)
Set the payload.
Definition at line 612 of file ccn_nametree.c.
static int ccny_skiplist_findbefore (struct ccn_nametree * h, const unsigned char * key, size_t size, struct ccny ** ans) [static]
Find the entry, or the one just before where it would go. The ans array is populated with pointers to the skiplinks at each level.
Returns:
1 if an exact match was found
Definition at line 187 of file ccn_nametree.c.
Referenced by ccn_nametree_look_ge(), ccn_nametree_look_gt(), ccn_nametree_look_le(), ccn_nametree_look_lt(), ccn_nametree_lookup(), ccny_skiplist_insert(), and ccny_skiplist_remove().
static ccn_cookie ccny_skiplist_insert (struct ccn_nametree * h, struct ccny * y) [static]
Insert an entry into the skiplist. Returns:
old cookie and does not insert if an exact key match is found
Definition at line 312 of file ccn_nametree.c.
Referenced by ccny_enroll().
static void ccny_skiplist_remove (struct ccn_nametree * h, struct ccny * y) [static]
Remove an entry from the skiplist. The entry must be present.
Definition at line 348 of file ccn_nametree.c.
Referenced by ccny_remove().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.