lib/ccn_signing.c
NAME
lib/ccn_signing.c -
Support for signing.
SYNOPSIS
Defines
#define is_left(x) (0 == (x & 1))
#define node_lr(x) (x & 1)
#define sibling_of(x) (x ^ 1)
#define parent_of(x) (x >> 1)
Functions
void * EVP_PKEY_get0 (EVP_PKEY *pkey)
int ccn_PKEY_assign (EVP_PKEY *pkey, int type, char *key)
int ccn_hmac_init (void *ctx, const void *key, int len, const EVP_MD *md)
int ccn_evp_sign_init (void *ctx, const void *key, int len, const EVP_MD *md)
int ccn_evp_verify_init (void *ctx, const void *key, int len, const EVP_MD *md)
int ccn_hmac_final (void *ctx, unsigned char *sigret, unsigned int *siglen, EVP_PKEY *pkey)
int ccn_hmac_verify_final (void *ctx, const unsigned char *sigret, unsigned int siglen, EVP_PKEY *pkey)
static void cleanup_evp_ctx (struct ccn_sigc *sigc)
static void cleanup_hmac_ctx (struct ccn_sigc *sigc)
static int sigc_from_digest_and_pkey (struct ccn_sigc *sigc, const char *digest, const struct ccn_pkey *pkey)
struct ccn_sigc * ccn_sigc_create (void)
void ccn_sigc_destroy (struct ccn_sigc **ctx)
int ccn_sigc_init (struct ccn_sigc *ctx, const char *digest, const struct ccn_pkey *key)
int ccn_sigc_update (struct ccn_sigc *ctx, const void *data, size_t size)
int ccn_sigc_final (struct ccn_sigc *ctx, struct ccn_signature *signature, size_t *size, const struct ccn_pkey *priv_key)
size_t ccn_sigc_signature_max_size (struct ccn_sigc *ctx, const struct ccn_pkey *key)
int ccn_merkle_root_hash (const unsigned char *msg, size_t size, const struct ccn_parsed_ContentObject *co, const EVP_MD *digest_type, MP_info *merkle_path_info, unsigned char *result, int result_size)
int ccn_verify_signature (const unsigned char *msg, size_t size, const struct ccn_parsed_ContentObject *co, const struct ccn_pkey *verification_key)
struct ccn_pkey * ccn_d2i_pubkey (const unsigned char *p, size_t size)
void ccn_pubkey_free (struct ccn_pkey *i_pubkey)
size_t ccn_pubkey_size (const struct ccn_pkey *i_pubkey)
int ccn_append_pubkey_blob (struct ccn_charbuf *c, const struct ccn_pkey *i_pubkey)
void ccn_random_bytes (unsigned char *buf, size_t size)
Generate pseudo-random bytes.
void ccn_add_entropy (const void *buf, size_t size, int bits_of_entropy)
Feed some entropy to the random number generator.
Detailed Description
Support for signing.
Part of the CCNx C Library.
Copyright (C) 2009-2010, 2013 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file ccn_signing.c.
Define Documentation
#define is_left(x) (0 == (x & 1))
Definition at line 306 of file ccn_signing.c.
#define node_lr(x) (x & 1)
Definition at line 307 of file ccn_signing.c.
#define parent_of(x) (x >> 1)
Definition at line 309 of file ccn_signing.c.
Referenced by ccn_merkle_root_hash().
#define sibling_of(x) (x ^ 1)
Definition at line 308 of file ccn_signing.c.
Function Documentation
void ccn_add_entropy (const void * buf, size_t size, int bits_of_entropy)
Feed some entropy to the random number generator. Parameters:
buf is the source buffer
size is in bytes
bits_of_entropy is an estimate; use 0 to make me guess
Definition at line 607 of file ccn_signing.c.
Referenced by main().
int ccn_append_pubkey_blob (struct ccn_charbuf * c, const struct ccn_pkey * i_pubkey)
Definition at line 559 of file ccn_signing.c.
Referenced by ccn_get_public_key(), ccn_sign_content(), and main().
struct ccn_pkey* ccn_d2i_pubkey (const unsigned char * p, size_t size) [read]
Definition at line 534 of file ccn_signing.c.
Referenced by ccn_cache_key(), and ccn_locate_key().
int ccn_evp_sign_init (void * ctx, const void * key, int len, const EVP_MD * md)
Definition at line 96 of file ccn_signing.c.
Referenced by sigc_from_digest_and_pkey().
int ccn_evp_verify_init (void * ctx, const void * key, int len, const EVP_MD * md)
Definition at line 101 of file ccn_signing.c.
Referenced by sigc_from_digest_and_pkey().
int ccn_hmac_final (void * ctx, unsigned char * sigret, unsigned int * siglen, EVP_PKEY * pkey)
Definition at line 106 of file ccn_signing.c.
Referenced by sigc_from_digest_and_pkey().
int ccn_hmac_init (void * ctx, const void * key, int len, const EVP_MD * md)
Definition at line 90 of file ccn_signing.c.
Referenced by sigc_from_digest_and_pkey().
int ccn_hmac_verify_final (void * ctx, const unsigned char * sigret, unsigned int siglen, EVP_PKEY * pkey)
Definition at line 112 of file ccn_signing.c.
Referenced by sigc_from_digest_and_pkey().
int ccn_merkle_root_hash (const unsigned char * msg, size_t size, const struct ccn_parsed_ContentObject * co, const EVP_MD * digest_type, MP_info * merkle_path_info, unsigned char * result, int result_size)
Definition at line 311 of file ccn_signing.c.
Referenced by ccn_verify_signature().
int ccn_PKEY_assign (EVP_PKEY * pkey, int type, char * key)
Definition at line 81 of file ccn_signing.c.
Referenced by ccn_aes_keystore_init().
void ccn_pubkey_free (struct ccn_pkey * i_pubkey)
Definition at line 543 of file ccn_signing.c.
Referenced by finalize_pkey().
size_t ccn_pubkey_size (const struct ccn_pkey * i_pubkey)
Definition at line 550 of file ccn_signing.c.
void ccn_random_bytes (unsigned char * buf, size_t size)
Generate pseudo-random bytes. Parameters:
buf is the destination buffer
size is in bytes
Definition at line 590 of file ccn_signing.c.
Referenced by ccn_name_append_nonce(), and main().
struct ccn_sigc* ccn_sigc_create (void) [read]
Definition at line 250 of file ccn_signing.c.
Referenced by ccn_encode_ContentObject(), and ccn_verify_signature().
void ccn_sigc_destroy (struct ccn_sigc ** ctx)
Definition at line 256 of file ccn_signing.c.
Referenced by ccn_encode_ContentObject(), and ccn_verify_signature().
int ccn_sigc_final (struct ccn_sigc * ctx, struct ccn_signature * signature, size_t * size, const struct ccn_pkey * priv_key)
Definition at line 286 of file ccn_signing.c.
Referenced by ccn_encode_ContentObject().
int ccn_sigc_init (struct ccn_sigc * ctx, const char * digest, const struct ccn_pkey * key)
Definition at line 267 of file ccn_signing.c.
Referenced by ccn_encode_ContentObject().
size_t ccn_sigc_signature_max_size (struct ccn_sigc * ctx, const struct ccn_pkey * key)
Definition at line 297 of file ccn_signing.c.
Referenced by ccn_encode_ContentObject().
int ccn_sigc_update (struct ccn_sigc * ctx, const void * data, size_t size)
Definition at line 278 of file ccn_signing.c.
Referenced by ccn_encode_ContentObject().
int ccn_verify_signature (const unsigned char * msg, size_t size, const struct ccn_parsed_ContentObject * co, const struct ccn_pkey * verification_key)
Definition at line 388 of file ccn_signing.c.
Referenced by ccn_dispatch_message(), ccn_verify_content(), decode_message(), and main().
static void cleanup_evp_ctx (struct ccn_sigc * sigc) [static]
Definition at line 124 of file ccn_signing.c.
Referenced by sigc_from_digest_and_pkey().
static void cleanup_hmac_ctx (struct ccn_sigc * sigc) [static]
Definition at line 128 of file ccn_signing.c.
Referenced by sigc_from_digest_and_pkey().
void* EVP_PKEY_get0 (EVP_PKEY * pkey)
Definition at line 76 of file ccn_signing.c.
Referenced by ccn_sigc_init(), ccn_verify_signature(), and main().
static int sigc_from_digest_and_pkey (struct ccn_sigc * sigc, const char * digest, const struct ccn_pkey * pkey) [static]
Definition at line 133 of file ccn_signing.c.
Referenced by ccn_sigc_init(), and ccn_verify_signature().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.