cmd/ccnnamelist.c
NAME
cmd/ccnnamelist.c -
Utility to print on standard output a list of names from ccnb-encoded data items in one or more files.
SYNOPSIS
Functions
static size_t process_data (struct ccn_skeleton_decoder *d, unsigned char *data, size_t n, struct ccn_charbuf *c, const struct options *o)
static int process_fd (int fd, struct ccn_charbuf *c, const struct options *o)
static int process_file (char *path, struct ccn_charbuf *c, const struct options *o)
static void usage (const char *progname)
int main (int argc, char *argv[])
Detailed Description
Utility to print on standard output a list of names from ccnb-encoded data items in one or more files.
A CCNx command-line utility.
Definition in file ccnnamelist.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 160 of file ccnnamelist.c.
static size_t process_data (struct ccn_skeleton_decoder * d, unsigned char * data, size_t n, struct ccn_charbuf * c, const struct options * o) [static]
Definition at line 47 of file ccnnamelist.c.
Referenced by process_fd().
static int process_fd (int fd, struct ccn_charbuf * c, const struct options * o) [static]
Definition at line 68 of file ccnnamelist.c.
Referenced by main(), and process_file().
static int process_file (char * path, struct ccn_charbuf * c, const struct options * o) [static]
Definition at line 128 of file ccnnamelist.c.
Referenced by main().
static void usage (const char * progname) [static]
Definition at line 148 of file ccnnamelist.c.
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.