include/ccn/flatname.h
NAME
include/ccn/flatname.h -
Flattened representation of a name.
SYNOPSIS
Defines
#define CCN_STRICT_PREFIX (-9999)
#define CCN_STRICT_REV_PREFIX 9999
#define CCNFLATDELIMSZ(rnc) ((rnc) & 3)
Get delimiter size from return value of ccn_flatname_next_comp.
#define CCNFLATDATASZ(rnc) ((rnc) >> 2)
Get data size from return value of ccn_flatname_next_comp.
#define CCNFLATSKIP(rnc) (CCNFLATDELIMSZ(rnc) + CCNFLATDATASZ(rnc))
Get total delimited size from return value of ccn_flatname_next_comp.
Functions
int ccn_flatname_append_component (struct ccn_charbuf *dst, const unsigned char *comp, size_t size)
Flat name representation.
int ccn_flatname_append_from_ccnb (struct ccn_charbuf *dst, const unsigned char *ccnb, size_t size, int skip, int count)
Append Components from a ccnb-encoded Name to a flatname.
int ccn_flatname_from_ccnb (struct ccn_charbuf *dst, const unsigned char *ccnb, size_t size)
Convert a ccnb-encoded Name to a flatname.
int ccn_name_append_flatname (struct ccn_charbuf *dst, const unsigned char *flatname, size_t size, int skip, int count)
Append Components from a flatname to a ccnb-encoded Name.
int ccn_uri_append_flatname (struct ccn_charbuf *uri, const unsigned char *flatname, size_t size, int includescheme)
Like ccn_uri_append(), but accepts a flatname instead of ccnb.
int ccn_flatname_ncomps (const unsigned char *flatname, size_t size)
Get flatname component count.
int ccn_flatname_charbuf_compare (struct ccn_charbuf *a, struct ccn_charbuf *b)
Flattened representation of a name.
int ccn_flatname_compare (const unsigned char *a, size_t al, const unsigned char *b, size_t bl)
Compare flatnames a and b (raw version).
int ccn_flatname_next_comp (const unsigned char *flatname, size_t size)
Parse the component delimiter from the start of a flatname.
Detailed Description
Flattened representation of a name.
Definition in file flatname.h.
Define Documentation
#define CCN_STRICT_PREFIX (-9999)
Definition at line 73 of file flatname.h.
Referenced by ccn_btree_compare(), ccn_flatname_compare(), content_matches_prefix(), r_store_content_matches_interest_prefix(), r_store_lookup_ccnb(), and testhelp_count_matches().
#define CCN_STRICT_REV_PREFIX 9999
Definition at line 74 of file flatname.h.
Referenced by ccn_flatname_compare().
#define CCNFLATDATASZ(rnc) ((rnc) >> 2)
Get data size from return value of ccn_flatname_next_comp.
Definition at line 87 of file flatname.h.
Referenced by ccn_btree_match_interest(), ccn_name_append_flatname(), and r_store_lookup_backwards().
#define CCNFLATDELIMSZ(rnc) ((rnc) & 3)
Get delimiter size from return value of ccn_flatname_next_comp.
Definition at line 85 of file flatname.h.
Referenced by ccn_btree_match_interest(), ccn_name_append_flatname(), and r_store_lookup_backwards().
#define CCNFLATSKIP(rnc) (CCNFLATDELIMSZ(rnc) + CCNFLATDATASZ(rnc))
Get total delimited size from return value of ccn_flatname_next_comp.
Definition at line 89 of file flatname.h.
Referenced by ccn_btree_match_interest(), ccn_flatname_ncomps(), and ccn_name_append_flatname().
Function Documentation
int ccn_flatname_append_component (struct ccn_charbuf * dst, const unsigned char * comp, size_t size)
Flat name representation. Internally, a name may be stored in a representation different than the ccnb encoding that is used on the wire. This encoding is designed so that simple lexical ordering on flatname byte arrays corresponds precisely with ccn's CanonicalOrdering of Names.
In the flatname representation, the bytes that constitute each Component are prepended by a length indicator that occupies one or more bytes. The high-order bit is used to mark the end of the length indicator, with 0 marking the last byte. The low order 7 bits of each of these bytes are concatenated together, in big endian order, to form the length.
For example: 0x00 => the zero-length component 0x01 0x41 => the component 'A' 0x7F 0xC1 ... => a component 127 bytes long that starts with '%C1' 0x81 0x00 0x39 ... => a component 128 bytes long that starts with '9' 0xff 0x3F 0x30 ... => a component 16383 bytes long that starts with '0'
Length indicators larger than this are possible in theory, but unlikely to come up in practice. Nonetheless, we do allow 3-byte length indicators.
Flat name representation.
Returns:
0, or -1 if there is an error.
Definition at line 65 of file ccn_flatname.c.
Referenced by ccn_flatname_append_from_ccnb(), process_incoming_content(), r_store_set_flatname(), and test_insert_content().
int ccn_flatname_append_from_ccnb (struct ccn_charbuf * dst, const unsigned char * ccnb, size_t size, int skip, int count)
Append Components from a ccnb-encoded Name to a flatname. The ccnb encoded input may be a ContentObject, Interest, Prefix, or Component instead of simply a Name.
Parameters:
dst is the destination, which should hold a ccnb-encoded Name
ccnb points to first byte of Name
size is the number of bytes in ccnb
skip is the number of components at the front of flatname to skip
count is the maximum number of componebts to append, or -1 for all
Returns:
number of appended components, or -1 if there is an error.
Definition at line 100 of file ccn_flatname.c.
Referenced by ccn_append_interest_bounds(), ccn_flatname_from_ccnb(), find_first_match_candidate(), process_incoming_content(), process_incoming_interest(), and test_flatname().
int ccn_flatname_charbuf_compare (struct ccn_charbuf * a, struct ccn_charbuf * b)
Flattened representation of a name. Compare flatnames a and b
Returns:
negative, 0, or positive if a < b, a == b, a > b, respectively. The special return value CCN_STRICT_PREFIX means a < b and a is also a prefix of b. Similarly CCN_STRICT_REV_PREFIX means b is a strict prefix of a.
Definition at line 34 of file ccn_flatname.c.
Referenced by r_store_content_matches_interest_prefix(), and r_store_lookup_ccnb().
int ccn_flatname_compare (const unsigned char * a, size_t al, const unsigned char * b, size_t bl)
Compare flatnames a and b (raw version).
Definition at line 43 of file ccn_flatname.c.
Referenced by ccn_flatname_charbuf_compare(), ccn_nametree_create(), and content_matches_prefix().
int ccn_flatname_from_ccnb (struct ccn_charbuf * dst, const unsigned char * ccnb, size_t size)
Convert a ccnb-encoded Name to a flatname. Returns:
number of components, or -1 if there is an error.
Definition at line 156 of file ccn_flatname.c.
Referenced by find_first_match_candidate(), next_child_at_level(), r_store_content_matches_interest_prefix(), r_store_find_first_match_candidate(), r_store_lookup_backwards(), r_store_lookup_ccnb(), r_store_next_child_at_level(), r_store_set_flatname(), test_flatname(), test_insert_content(), and testhelp_count_matches().
int ccn_flatname_ncomps (const unsigned char * flatname, size_t size)
Get flatname component count. Returns:
the number of name components in the flatname, or -1 if the flatname is not well-formed
Definition at line 266 of file ccn_flatname.c.
Referenced by ccn_btree_insert_content(), and test_flatname().
int ccn_flatname_next_comp (const unsigned char * flatname, size_t size)
Parse the component delimiter from the start of a flatname. The delimiter size is limited to 3 bytes.
Returns:
-1 for error, 0 nothing left, or compsize * 4 + delimsize
Definition at line 170 of file ccn_flatname.c.
Referenced by ccn_btree_match_interest(), ccn_flatname_ncomps(), ccn_name_append_flatname(), and r_store_lookup_backwards().
int ccn_name_append_flatname (struct ccn_charbuf * dst, const unsigned char * flatname, size_t size, int skip, int count)
Append Components from a flatname to a ccnb-encoded Name. Parameters:
dst is the destination, which should hold a ccnb-encoded Name
flatname points to first byte of flatname
size is the number of bytes in flatname
skip is the number of components at the front of flatname to skip
count is the maximum number of components to append, or -1 for all
Returns:
number of appended components, or -1 if there is an error.
Definition at line 199 of file ccn_flatname.c.
Referenced by ccn_uri_append_flatname(), match_interests(), next_child_at_level(), r_store_name_append_components(), r_store_next_child_at_level(), and test_flatname().
int ccn_uri_append_flatname (struct ccn_charbuf * uri, const unsigned char * flatname, size_t size, int includescheme)
Like ccn_uri_append(), but accepts a flatname instead of ccnb.
Definition at line 238 of file ccn_flatname.c.
Referenced by ccnd_debug_content(), ccnr_debug_content(), test_flatname(), and test_insert_content().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.