.TH "keystore_header_st" 3 "9 Oct 2013" "Version 0.8.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
keystore_header_st \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBinitialized\fP"
.br
.ti -1c
.RI "ssize_t(* \fBdigest_length_func\fP )(struct ccn_keystore *p)"
.br
.ti -1c
.RI "const unsigned char *(* \fBdigest_func\fP )(struct ccn_keystore *p)"
.br
.ti -1c
.RI "struct ccn_pkey *(* \fBkey_func\fP )(struct ccn_keystore *p)"
.br
.ti -1c
.RI "const char *(* \fBdigest_algorithm_func\fP )(struct ccn_keystore *p)"
.br
.ti -1c
.RI "void(* \fBdestroy_func\fP )(struct ccn_keystore **p)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file keystore.h.
.SH "Field Documentation"
.PP 
.SS "void(* \fBkeystore_header_st::destroy_func\fP)(struct ccn_keystore **p)"
.PP
Definition at line 57 of file keystore.h.
.SS "const char*(* \fBkeystore_header_st::digest_algorithm_func\fP)(struct ccn_keystore *p)"
.PP
Definition at line 56 of file keystore.h.
.SS "const unsigned char*(* \fBkeystore_header_st::digest_func\fP)(struct ccn_keystore *p)"
.PP
Definition at line 54 of file keystore.h.
.SS "ssize_t(* \fBkeystore_header_st::digest_length_func\fP)(struct ccn_keystore *p)"
.PP
Definition at line 53 of file keystore.h.
.SS "int \fBkeystore_header_st::initialized\fP"
.PP
Definition at line 52 of file keystore.h.
.SS "struct ccn_pkey*(* \fBkeystore_header_st::key_func\fP)(struct ccn_keystore *p)\fC [read]\fP"
.PP
Definition at line 55 of file keystore.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
