include/ccn/openssl_ex.h
NAME
include/ccn/openssl_ex.h -
OpenSSL extension interface.
SYNOPSIS
Defines
#define NEED_OPENSSL_1_0_COMPAT
Functions
void * EVP_PKEY_get0 (EVP_PKEY *pkey)
EVP_PKEY * EVP_PKEY_new_mac_key (int type, ENGINE *e, const unsigned char *key, int keylen)
int ccn_PKEY_assign (EVP_PKEY *pkey, int type, char *key)
Detailed Description
OpenSSL extension interface.
Used to define our own OpenSSL 1.0.X extensions that will go away when we switch to OpenSSL 1.0.X
Part of the CCNx C Library.
Copyright (C) 2013 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file openssl_ex.h.
Define Documentation
#define NEED_OPENSSL_1_0_COMPAT
Definition at line 33 of file openssl_ex.h.
Function Documentation
int ccn_PKEY_assign (EVP_PKEY * pkey, int type, char * key)
Definition at line 81 of file ccn_signing.c.
Referenced by ccn_aes_keystore_init().
void* EVP_PKEY_get0 (EVP_PKEY * pkey)
Definition at line 76 of file ccn_signing.c.
Referenced by ccn_sigc_init(), ccn_verify_signature(), and main().
EVP_PKEY* EVP_PKEY_new_mac_key (int type, ENGINE * e, const unsigned char * key, int keylen)
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.