lib/signbenchtest.c
NAME
lib/signbenchtest.c -
A simple test program to benchmark signing performance.
SYNOPSIS
Defines
#define FRESHNESS 10
#define COUNT 3000
#define PAYLOAD_SIZE 51
#define PASSWORD 'Th1s1sn0t8g00dp8ssw0rd.'
Functions
static void usage (const char *progname)
int main (int argc, char **argv)
Detailed Description
A simple test program to benchmark signing performance.
Copyright (C) 2009,2013 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file signbenchtest.c.
Define Documentation
#define COUNT 3000
Definition at line 31 of file signbenchtest.c.
Referenced by main().
#define FRESHNESS 10
Definition at line 30 of file signbenchtest.c.
Referenced by main().
#define PASSWORD 'Th1s1sn0t8g00dp8ssw0rd.'
Definition at line 34 of file signbenchtest.c.
Referenced by main().
#define PAYLOAD_SIZE 51
Definition at line 32 of file signbenchtest.c.
Referenced by main().
Function Documentation
int main (int argc, char ** argv)
Definition at line 47 of file signbenchtest.c.
static void usage (const char * progname) [static]
Definition at line 37 of file signbenchtest.c.
Referenced by initialize(), main(), parseopts(), and process_options().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.