.TH "include/ccn/siphash24.h" 3 "9 Oct 2013" "Version 0.8.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ccn/siphash24.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "uint64_t \fBsiphash_2_4\fP (const unsigned char *in, size_t inlen, const unsigned char *k)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint64_t siphash_2_4 (const unsigned char * in, size_t inlen, const unsigned char * k)"
.PP
Definition at line 51 of file siphash24.c.
.PP
Referenced by hashtb_hash().
.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
