sync/sync_api.c
NAME
sync/sync_api.c -
Sync library interface.
SYNOPSIS
Enumerations
enum local_flags { LF_NULL, LF_ADVISE, LF_NODE, LF_OTHER }
Functions
struct ccns_slice * ccns_slice_create ()
Allocate a ccns_slice structure.
void ccns_slice_destroy (struct ccns_slice **sp)
Deallocate a ccns_slice structure.
int ccns_slice_add_clause (struct ccns_slice *s, struct ccn_charbuf *c)
Add a (filter) clause to a ccns_slice structure.
int ccns_slice_set_topo_prefix (struct ccns_slice *s, struct ccn_charbuf *t, struct ccn_charbuf *p)
static int append_slice (struct ccn_charbuf *c, struct ccns_slice *s)
static int slice_parse (struct ccns_slice *s, const unsigned char *p, size_t size)
int ccns_slice_name (struct ccn_charbuf *nm, struct ccns_slice *s)
Construct the name of a Sync configuration slice based on the parameters.
int ccns_read_slice (struct ccn *h, struct ccn_charbuf *name, struct ccns_slice *slice)
Read a slice (from a repository) given the name.
struct ccn_charbuf * make_scope1_template (void)
static enum ccn_upcall_res write_interest_handler (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
static int write_slice (struct ccn *h, struct ccns_slice *slice, struct ccn_charbuf *name)
int ccns_write_slice (struct ccn *h, struct ccns_slice *slice, struct ccn_charbuf *name)
Write a ccns_slice object to a repository.
int ccns_delete_slice (struct ccn *h, struct ccn_charbuf *name)
Delete a ccns_slice object from a repository.
static void gettime (const struct ccn_gettime *self, struct ccn_timeval *result)
static int start_interest (struct sync_diff_data *diff_data)
static void my_r_sync_msg (struct sync_plumbing *sd, const char *fmt,...)
static struct SyncNodeComposite * extractNode (struct SyncRootStruct *root, struct ccn_upcall_info *info)
static struct sync_diff_fetch_data * find_fetch_data (struct ccns_handle *ch, struct SyncHashCacheEntry *ce)
static int delink_fetch_data (struct ccns_handle *ch, struct sync_diff_fetch_data *fd)
static void free_fetch_data (struct ccns_handle *ch, struct sync_diff_fetch_data *fd)
static void setCurrentHash (struct SyncRootStruct *root, struct SyncHashCacheEntry *ce)
static struct SyncHashCacheEntry * chooseNextHash (struct ccns_handle *ch)
static int each_round (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
static void start_round (struct ccns_handle *ch, int micros)
static enum ccn_upcall_res my_response (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
static struct ccn_charbuf * make_ra_template (struct ccns_handle *ch, struct ccn_charbuf *c)
static int my_get (struct sync_diff_get_closure *gc, struct sync_diff_fetch_data *fd)
static int my_add (struct sync_diff_add_closure *ac, struct ccn_charbuf *name)
static int note_update_done (struct sync_done_closure *dc)
struct ccns_handle * ccns_open (struct ccn *h, struct ccns_slice *slice, struct ccns_name_closure *nc, struct ccn_charbuf *rhash, struct ccn_charbuf *pname)
Start notification of addition of names to a sync slice.
void ccns_close (struct ccns_handle **sh, struct ccn_charbuf *rhash, struct ccn_charbuf *pname)
Stop notification of changes of names in a sync slice and free the handle.
Variables
static struct sync_plumbing_client_methods client_methods
Detailed Description
Sync library interface.
Implements a library interface to the Sync protocol facilities implemented by the Repository
Part of the CCNx C Library.
Copyright (C) 2012-2013 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file sync_api.c.
Enumeration Type Documentation
enum local_flags
Enumerator:
LF_NULL
LF_ADVISE
LF_NODE
LF_OTHER
Definition at line 532 of file sync_api.c.
Function Documentation
static int append_slice (struct ccn_charbuf * c, struct ccns_slice * s) [static]
Definition at line 169 of file sync_api.c.
Referenced by ccns_slice_name(), and write_slice().
void ccns_close (struct ccns_handle ** sh, struct ccn_charbuf * rhash, struct ccn_charbuf * pname)
Stop notification of changes of names in a sync slice and free the handle. Parameters:
sh is a pointer (to a pointer) to the sync handle returned by ccns_open, which will be freed and set to NULL.
rhash if non-NULL will be filled in with the current root hash.
pname if non-NULL will be filled in with the starting name for enumeration within the sync tree represented by the root hash rhash.
Definition at line 1202 of file sync_api.c.
Referenced by main().
int ccns_delete_slice (struct ccn * h, struct ccn_charbuf * name)
Delete a ccns_slice object from a repository. Parameters:
h is the ccn_handle on which to write.
name is a pointer to a charbuf naming the slice to be deleted.
Returns:
0 on success, -1 otherwise.
Definition at line 502 of file sync_api.c.
Referenced by main().
struct ccns_handle* ccns_open (struct ccn * h, struct ccns_slice * slice, struct ccns_name_closure * nc, struct ccn_charbuf * rhash, struct ccn_charbuf * pname) [read]
Start notification of addition of names to a sync slice. Parameters:
h is the ccn_handle on which to communicate.
slice is the slice to be opened.
nc is the closure which will be called for each new name, and returns 0 to continue enumeration, -1 to stop further enumeration. NOTE: It is not safe to call ccns_close from within the callback.
rhash If NULL, indicates that the enumeration should start from the empty set. If non-NULL but empty, indicates that the enumeration should start from the current root. If non-NULL, and not empty, indicates that the enumeration should start from the specified root hash
pname if non-NULL represents the starting name for enumeration within the sync tree represented by the root hash rhash.
Returns:
a pointer to a new sync handle, which will be freed at close.
Definition at line 1119 of file sync_api.c.
Referenced by main().
int ccns_read_slice (struct ccn * h, struct ccn_charbuf * name, struct ccns_slice * slice)
Read a slice (from a repository) given the name. Read a slice given the name.
Parameters:
h is the ccn_handle on which to read.
name is the charbuf containing the name of the sync slice to be read.
slice is a pointer to a ccns_slice object which will be filled in on successful return.
Returns:
0 on success, -1 otherwise.
Definition at line 303 of file sync_api.c.
int ccns_slice_add_clause (struct ccns_slice * s, struct ccn_charbuf * f)
Add a (filter) clause to a ccns_slice structure. Parameters:
s is the slice to be modified
f is a filter clause ccnb-encoded as a Name
Returns:
0 on success, -1 otherwise.
Definition at line 119 of file sync_api.c.
Referenced by main(), and slice_parse().
struct ccns_slice* ccns_slice_create (void) [read]
Allocate a ccns_slice structure. Returns:
a pointer to a new ccns_slice structure
Definition at line 79 of file sync_api.c.
Referenced by main().
void ccns_slice_destroy (struct ccns_slice ** sp)
Deallocate a ccns_slice structure. Parameters:
sp is a pointer to a pointer to a ccns_slice structure. The pointer will be set to NULL on return.
Definition at line 98 of file sync_api.c.
Referenced by main().
int ccns_slice_name (struct ccn_charbuf * nm, struct ccns_slice * s)
Construct the name of a Sync configuration slice based on the parameters. Construct the name of a Sync configuration slice.
Parameters:
nm is the ccn_charbuf which will be set to the ccnb encoded Name
s is the definition of the slice for which the name is required.
Returns:
a ccn_charbuf with the ccnb encoded Name of the slice.
Definition at line 259 of file sync_api.c.
Referenced by ccns_write_slice(), and main().
int ccns_slice_set_topo_prefix (struct ccns_slice * s, struct ccn_charbuf * t, struct ccn_charbuf * p)
Definition at line 149 of file sync_api.c.
Referenced by main().
int ccns_write_slice (struct ccn * h, struct ccns_slice * slice, struct ccn_charbuf * name)
Write a ccns_slice object to a repository. Parameters:
h is the ccn_handle on which to write.
slice is a pointer to a ccns_slice object to be written.
name if non-NULL, is a pointer to a charbuf which will be filled in with the name of the slice that was written.
Returns:
0 on success, -1 otherwise.
Definition at line 469 of file sync_api.c.
Referenced by main().
static struct SyncHashCacheEntry* chooseNextHash (struct ccns_handle * ch) [static, read]
Definition at line 646 of file sync_api.c.
Referenced by each_round().
static int delink_fetch_data (struct ccns_handle * ch, struct sync_diff_fetch_data * fd) [static]
Definition at line 606 of file sync_api.c.
Referenced by free_fetch_data().
static int each_round (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Definition at line 668 of file sync_api.c.
Referenced by start_round().
static struct SyncNodeComposite* extractNode (struct SyncRootStruct * root, struct ccn_upcall_info * info) [static, read]
Definition at line 566 of file sync_api.c.
Referenced by my_response().
static struct sync_diff_fetch_data* find_fetch_data (struct ccns_handle * ch, struct SyncHashCacheEntry * ce) [static, read]
Definition at line 595 of file sync_api.c.
Referenced by chooseNextHash().
static void free_fetch_data (struct ccns_handle * ch, struct sync_diff_fetch_data * fd) [static]
Definition at line 625 of file sync_api.c.
Referenced by ccns_close(), my_response(), and start_interest().
static void gettime (const struct ccn_gettime * self, struct ccn_timeval * result) [static]
Definition at line 523 of file sync_api.c.
Referenced by ccns_open().
static struct ccn_charbuf* make_ra_template (struct ccns_handle * ch, struct ccn_charbuf * c) [static, read]
Definition at line 890 of file sync_api.c.
Referenced by start_interest().
struct ccn_charbuf* make_scope1_template (void) [read]
Definition at line 343 of file sync_api.c.
Referenced by write_slice().
static int my_add (struct sync_diff_add_closure * ac, struct ccn_charbuf * name) [static]
Definition at line 1024 of file sync_api.c.
Referenced by ccns_open().
static int my_get (struct sync_diff_get_closure * gc, struct sync_diff_fetch_data * fd) [static]
Definition at line 974 of file sync_api.c.
Referenced by ccns_open().
static void my_r_sync_msg (struct sync_plumbing * sd, const char * fmt, ...) [static]
Definition at line 554 of file sync_api.c.
static enum ccn_upcall_res my_response (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info) [static]
Definition at line 755 of file sync_api.c.
Referenced by my_get(), and start_interest().
static int note_update_done (struct sync_done_closure * dc) [static]
Definition at line 1090 of file sync_api.c.
Referenced by ccns_open().
static void setCurrentHash (struct SyncRootStruct * root, struct SyncHashCacheEntry * ce) [static]
Definition at line 638 of file sync_api.c.
Referenced by my_add(), and note_update_done().
static int slice_parse (struct ccns_slice * s, const unsigned char * p, size_t size) [static]
Definition at line 192 of file sync_api.c.
Referenced by ccns_read_slice().
static int start_interest (struct sync_diff_data * diff_data) [static]
Definition at line 918 of file sync_api.c.
Referenced by each_round().
static void start_round (struct ccns_handle * ch, int micros) [static]
Definition at line 738 of file sync_api.c.
Referenced by ccns_open(), my_add(), and my_response().
static enum ccn_upcall_res write_interest_handler (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info) [static]
Definition at line 355 of file sync_api.c.
Referenced by write_slice().
static int write_slice (struct ccn * h, struct ccns_slice * slice, struct ccn_charbuf * name) [static]
Definition at line 376 of file sync_api.c.
Referenced by ccns_delete_slice(), and ccns_write_slice().
Variable Documentation
struct sync_plumbing_client_methods client_methods [static]"Initial value:
 {
    my_r_sync_msg, NULL, NULL, NULL, NULL, NULL
}
Definition at line 1114 of file sync_api.c.
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.