sync/SyncActions.c
NAME
sync/SyncActions.c -
Part of CCNx Sync.
SYNOPSIS
Defines
#define M 1000000
#define SYNC_UPDATE_VERSION (20120307)
#define StatsLine(XXX)
Enumerations
enum SyncCompareState { SyncCompare_init, SyncCompare_preload, SyncCompare_busy, SyncCompare_waiting, SyncCompare_done }
enum SyncUpdateState { SyncUpdate_init, SyncUpdate_inserted, SyncUpdate_busy, SyncUpdate_error, SyncUpdate_done }
Functions
static int HeartbeatAction (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
static int UpdateAction (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
static int CompareAction (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
static int SyncUpdateRoot (struct SyncRootStruct *root)
static int SyncSendRootAdviseInterest (struct SyncRootStruct *root)
static int SyncStartCompareAction (struct SyncRootStruct *root, struct ccn_charbuf *hashR)
static int SyncRegisterInterests (struct SyncRootStruct *root)
static int showCacheEntry (struct SyncRootStruct *root, char *dst, int lim, char *prefix, struct SyncHashCacheEntry *ce)
static void showCacheEntry1 (struct SyncRootStruct *root, char *here, char *msg, struct SyncHashCacheEntry *ce)
static void showCacheEntry2 (struct SyncRootStruct *root, char *here, char *msg, struct SyncHashCacheEntry *ce1, struct SyncHashCacheEntry *ce2)
static struct SyncActionData * newActionData (enum SyncRegisterActionKind kind)
static void linkActionData (struct SyncRootStruct *root, struct SyncActionData *data)
static void delinkActionData (struct SyncActionData *data)
static int moveActionData (struct SyncActionData *data, enum SyncActionState dstState)
static struct SyncActionData * destroyActionData (struct SyncActionData *data)
static char * getCmdStr (enum SyncRegisterActionKind kind)
static char * getKindStr (enum SyncRegisterActionKind kind)
static void setCovered (struct SyncHashCacheEntry *ce)
static int isCovered (struct SyncHashCacheEntry *ce)
static int reportExclude (struct SyncRootStruct *root, struct ccn_buf_decoder *d)
static void kickCompare (struct SyncCompareData *scd, struct SyncActionData *action)
static void kickHeartBeat (struct SyncRootStruct *root, int micros)
static struct ccn_charbuf * formatStats (struct SyncRootStruct *root, struct ccn_charbuf *cb)
static struct ccn_charbuf * constructCommandPrefix (struct SyncRootStruct *root, enum SyncRegisterActionKind kind)
static int extractDeltas (struct SyncRootStruct *root, struct ccn_upcall_info *info)
static struct SyncNodeComposite * extractNode (struct SyncRootStruct *root, struct ccn_upcall_info *info)
static int noteHash (struct SyncRootStruct *root, struct SyncHashCacheEntry *ce, int add, int remote)
static struct SyncHashInfoList * chooseRemoteHash (struct SyncRootStruct *root)
static int fauxError (struct SyncBaseStruct *base)
static void destroyCompareData (struct SyncCompareData *data)
static void abortCompare (struct SyncCompareData *data, char *why)
static int extractBuf (struct ccn_charbuf *cb, struct SyncNodeComposite *nc, struct SyncNodeElem *ne)
static struct SyncHashCacheEntry * ensureRemoteEntry (struct SyncCompareData *data, const unsigned char *xp, ssize_t xs)
static struct SyncHashCacheEntry * cacheEntryForElem (struct SyncCompareData *data, struct SyncNodeComposite *nc, struct SyncNodeElem *ne, int remote)
static enum ccn_upcall_res SyncRemoteFetchResponse (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
static int SyncStartNodeFetch (struct SyncRootStruct *root, struct SyncHashCacheEntry *ce, struct SyncCompareData *comp)
static int comparisonFailed (struct SyncCompareData *data, char *why, int line)
static int addNameFromCompare (struct SyncCompareData *data)
static int doPreload (struct SyncCompareData *data)
static int doComparison (struct SyncCompareData *data)
static void purgeOldEntries (struct SyncRootStruct *root)
static int SyncStartContentFetch (struct SyncRootStruct *root, struct ccn_charbuf *name, struct SyncCompareData *comp)
static struct SyncHashCacheEntry * newNodeCommon (struct SyncRootStruct *root, struct SyncNodeAccum *nodes, struct SyncNodeComposite *nc)
static struct SyncHashCacheEntry * nodeFromNodes (struct SyncRootStruct *root, struct SyncNodeAccum *na)
static int SyncStartSliceEnum (struct SyncRootStruct *root)
static void setFence (struct SyncBaseStruct *base)
int SyncStartHeartbeat (struct SyncBaseStruct *base)
static struct SyncActionData * SyncFindAction (struct SyncRootStruct *root, enum SyncRegisterActionKind kind)
static int findAndDeleteRoot (struct SyncBaseStruct *base, char *here, const unsigned char *hp, ssize_t hs)
static int SyncHandleSlice (struct SyncBaseStruct *base, struct ccn_charbuf *name)
static void HoldInterest (struct SyncRootStruct *root, struct ccn_upcall_info *info)
static void CheckHeldInterest (struct SyncRootStruct *root, struct ccn_charbuf *cob)
static void ReprocessHeldInterest (struct SyncRootStruct *root)
static struct SyncRootDeltas * NewDeltas (struct SyncRootStruct *root)
static struct SyncRootDeltas * FreeDeltas (struct SyncRootDeltas *deltas)
static int RemRootDeltas (struct SyncRootStruct *root, struct SyncRootDeltas *deltas)
static int SendDeltasReply (struct SyncRootStruct *root, struct SyncRootDeltas *deltas)
static struct SyncHashInfoList * scanRemoteSeen (struct SyncRootStruct *root, struct SyncHashCacheEntry *ceR)
static struct SyncRootDeltas * CloseUpdateCoding (struct SyncUpdateData *ud)
static struct SyncRootDeltas * scanDeltas (struct SyncRootStruct *root, struct SyncHashCacheEntry *ceR)
static enum ccn_upcall_res SyncInterestArrived (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
static int SyncRegisterInterest (struct SyncRootStruct *root, enum SyncRegisterActionKind kind)
static enum ccn_upcall_res SyncRootAdviseResponse (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
static int MakeNodeFromNames (struct SyncUpdateData *ud, int split)
static int TryNodeSplit (struct SyncUpdateData *ud)
static int AddUpdateName (struct SyncUpdateData *ud, struct ccn_charbuf *name, int isNew)
static int SyncTreeMergeNames (struct SyncTreeWorkerHead *head, struct SyncUpdateData *ud)
static struct SyncUpdateData * FreeUpdateData (struct SyncUpdateData *ud)
static int sync_start_for_actions (struct sync_plumbing *sd, struct ccn_charbuf *state_buf)
static int sync_notify_for_actions (struct sync_plumbing *sd, struct ccn_charbuf *name, int enum_index, uint64_t seq_num)
static void sync_stop_for_actions (struct sync_plumbing *sd, struct ccn_charbuf *state_buf)
struct SyncBaseStruct * SyncNewBaseForActions (struct sync_plumbing *sd)
construct a new base with methods at the SyncActions level
Variables
static int useCompExcl = 1
static int showHighLevel = 1
static int nDeltasLimit = 4
static int cachePurgeTrigger = 60
static int cacheCleanBatch = 8
static int cacheCleanDelta = 4
static int adviseNeedReset = 1
static int updateStallDelta = 15
static int updateNeedDelta = 6
static int fenceSeconds = 2
static int shortDelayMicros = 1000
static int compareAssumeBad = 20
static int nodeSplitTrigger = 4000
static int hashSplitTrigger = 17
static int namesYieldInc = 100
static int namesYieldMicros = 20*1000
struct sync_plumbing_sync_methods syncActionMethods
Detailed Description
Part of CCNx Sync.
Definition in file SyncActions.c.
Define Documentation
#define M 1000000
Definition at line 42 of file SyncActions.c.
Referenced by chooseRemoteHash(), formatStats(), GetCurrentTime(), GetCurrentTimeUSecs(), HeartbeatAction(), MilliSleep(), purgeOldEntries(), and SyncCurrentTime().
#define StatsLine(XXX)"Value:
if (stats->XXX) \
pos += snprintf(s+pos, lim-pos, ', %s %ju', #XXX, (uintmax_t) stats->XXX);
Definition at line 415 of file SyncActions.c.
Referenced by formatStats().
#define SYNC_UPDATE_VERSION (20120307)
Definition at line 62 of file SyncActions.c.
Referenced by extractDeltas(), and NewDeltas().
Enumeration Type Documentation
enum SyncCompareState
Enumerator:
SyncCompare_init
SyncCompare_preload
SyncCompare_busy
SyncCompare_waiting
SyncCompare_done
Definition at line 64 of file SyncActions.c.
enum SyncUpdateState
Enumerator:
SyncUpdate_init
SyncUpdate_inserted
SyncUpdate_busy
SyncUpdate_error
SyncUpdate_done
Definition at line 99 of file SyncActions.c.
Function Documentation
static void abortCompare (struct SyncCompareData * data, char * why) [static]
Definition at line 779 of file SyncActions.c.
Referenced by CompareAction(), and HeartbeatAction().
static int addNameFromCompare (struct SyncCompareData * data) [static]
Definition at line 1169 of file SyncActions.c.
Referenced by doComparison().
static int AddUpdateName (struct SyncUpdateData * ud, struct ccn_charbuf * name, int isNew) [static]
Definition at line 3282 of file SyncActions.c.
Referenced by SyncTreeMergeNames().
static struct SyncHashCacheEntry* cacheEntryForElem (struct SyncCompareData * data, struct SyncNodeComposite * nc, struct SyncNodeElem * ne, int remote) [static, read]
Definition at line 849 of file SyncActions.c.
Referenced by doComparison(), and doPreload().
static void CheckHeldInterest (struct SyncRootStruct * root, struct ccn_charbuf * cob) [static]
Definition at line 2316 of file SyncActions.c.
Referenced by SendDeltasReply(), and SyncInterestArrived().
static struct SyncHashInfoList* chooseRemoteHash (struct SyncRootStruct * root) [static, read]
Definition at line 702 of file SyncActions.c.
Referenced by HeartbeatAction().
static struct SyncRootDeltas* CloseUpdateCoding (struct SyncUpdateData * ud) [static, read]
Definition at line 2477 of file SyncActions.c.
Referenced by UpdateAction().
static int CompareAction (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Definition at line 1577 of file SyncActions.c.
Referenced by kickCompare().
static int comparisonFailed (struct SyncCompareData * data, char * why, int line) [static]
Definition at line 1162 of file SyncActions.c.
Referenced by doComparison().
static struct ccn_charbuf* constructCommandPrefix (struct SyncRootStruct * root, enum SyncRegisterActionKind kind) [static, read]
Definition at line 531 of file SyncActions.c.
Referenced by SendDeltasReply(), SyncRegisterInterest(), SyncSendRootAdviseInterest(), and SyncStartNodeFetch().
static void delinkActionData (struct SyncActionData * data) [static]
Definition at line 212 of file SyncActions.c.
Referenced by destroyActionData(), and moveActionData().
static struct SyncActionData* destroyActionData (struct SyncActionData * data) [static, read]
Definition at line 283 of file SyncActions.c.
Referenced by CompareAction(), destroyCompareData(), doPreload(), SyncInterestArrived(), SyncRegisterInterest(), SyncRemoteFetchResponse(), SyncRootAdviseResponse(), SyncSendRootAdviseInterest(), SyncStartContentFetch(), and SyncStartNodeFetch().
static void destroyCompareData (struct SyncCompareData * data) [static]
Definition at line 746 of file SyncActions.c.
Referenced by abortCompare(), and CompareAction().
static int doComparison (struct SyncCompareData * data) [static]
Definition at line 1265 of file SyncActions.c.
Referenced by CompareAction().
static int doPreload (struct SyncCompareData * data) [static]
Definition at line 1194 of file SyncActions.c.
Referenced by CompareAction().
static struct SyncHashCacheEntry* ensureRemoteEntry (struct SyncCompareData * data, const unsigned char * xp, ssize_t xs) [static, read]
Definition at line 833 of file SyncActions.c.
Referenced by cacheEntryForElem().
static int extractBuf (struct ccn_charbuf * cb, struct SyncNodeComposite * nc, struct SyncNodeElem * ne) [static]
Definition at line 824 of file SyncActions.c.
Referenced by doComparison(), and SyncTreeMergeNames().
static int extractDeltas (struct SyncRootStruct * root, struct ccn_upcall_info * info) [static]
Definition at line 554 of file SyncActions.c.
Referenced by SyncRootAdviseResponse().
static struct SyncNodeComposite* extractNode (struct SyncRootStruct * root, struct ccn_upcall_info * info) [static, read]
Definition at line 601 of file SyncActions.c.
Referenced by SyncRemoteFetchResponse(), and SyncRootAdviseResponse().
static int fauxError (struct SyncBaseStruct * base) [static]
Definition at line 729 of file SyncActions.c.
Referenced by SyncRemoteFetchResponse(), and SyncRootAdviseResponse().
static int findAndDeleteRoot (struct SyncBaseStruct * base, char * here, const unsigned char * hp, ssize_t hs) [static]
Definition at line 2105 of file SyncActions.c.
Referenced by SyncHandleSlice().
static struct ccn_charbuf* formatStats (struct SyncRootStruct * root, struct ccn_charbuf * cb) [static, read]
Definition at line 420 of file SyncActions.c.
Referenced by CompareAction(), SyncInterestArrived(), and UpdateAction().
static struct SyncRootDeltas* FreeDeltas (struct SyncRootDeltas * deltas) [static, read]
Definition at line 2353 of file SyncActions.c.
Referenced by CloseUpdateCoding(), FreeUpdateData(), RemRootDeltas(), and UpdateAction().
static struct SyncUpdateData* FreeUpdateData (struct SyncUpdateData * ud) [static, read]
Definition at line 3459 of file SyncActions.c.
Referenced by SyncUpdateRoot(), and UpdateAction().
static char* getCmdStr (enum SyncRegisterActionKind kind) [static]
Definition at line 300 of file SyncActions.c.
Referenced by constructCommandPrefix().
static char* getKindStr (enum SyncRegisterActionKind kind) [static]
Definition at line 316 of file SyncActions.c.
Referenced by SyncInterestArrived(), and SyncRegisterInterest().
static int HeartbeatAction (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Definition at line 1914 of file SyncActions.c.
Referenced by kickHeartBeat(), and SyncStartHeartbeat().
static void HoldInterest (struct SyncRootStruct * root, struct ccn_upcall_info * info) [static]
Definition at line 2285 of file SyncActions.c.
Referenced by SyncInterestArrived().
static int isCovered (struct SyncHashCacheEntry * ce) [static]
Definition at line 353 of file SyncActions.c.
Referenced by doComparison(), doPreload(), noteHash(), SyncInterestArrived(), SyncRemoteFetchResponse(), and SyncRootAdviseResponse().
static void kickCompare (struct SyncCompareData * scd, struct SyncActionData * action) [static]
Definition at line 392 of file SyncActions.c.
Referenced by SyncRemoteFetchResponse(), and SyncStartCompareAction().
static void kickHeartBeat (struct SyncRootStruct * root, int micros) [static]
Definition at line 406 of file SyncActions.c.
Referenced by UpdateAction().
static void linkActionData (struct SyncRootStruct * root, struct SyncActionData * data) [static]
Definition at line 203 of file SyncActions.c.
Referenced by SyncRegisterInterest(), SyncSendRootAdviseInterest(), SyncStartContentFetch(), and SyncStartNodeFetch().
static int MakeNodeFromNames (struct SyncUpdateData * ud, int split) [static]
Definition at line 3133 of file SyncActions.c.
Referenced by TryNodeSplit(), and UpdateAction().
static int moveActionData (struct SyncActionData * data, enum SyncActionState dstState) [static]
Definition at line 257 of file SyncActions.c.
Referenced by SyncRemoteFetchResponse().
static struct SyncActionData* newActionData (enum SyncRegisterActionKind kind) [static, read]
Definition at line 194 of file SyncActions.c.
Referenced by SyncRegisterInterest(), SyncSendRootAdviseInterest(), SyncStartContentFetch(), and SyncStartNodeFetch().
static struct SyncRootDeltas* NewDeltas (struct SyncRootStruct * root) [static, read]
Definition at line 2339 of file SyncActions.c.
Referenced by SyncUpdateRoot().
static struct SyncHashCacheEntry* newNodeCommon (struct SyncRootStruct * root, struct SyncNodeAccum * nodes, struct SyncNodeComposite * nc) [static, read]
Definition at line 1730 of file SyncActions.c.
Referenced by MakeNodeFromNames(), and nodeFromNodes().
static struct SyncHashCacheEntry* nodeFromNodes (struct SyncRootStruct * root, struct SyncNodeAccum * na) [static, read]
Definition at line 1796 of file SyncActions.c.
Referenced by UpdateAction().
static int noteHash (struct SyncRootStruct * root, struct SyncHashCacheEntry * ce, int add, int remote) [static]
Definition at line 634 of file SyncActions.c.
Referenced by SyncInterestArrived(), SyncRootAdviseResponse(), and UpdateAction().
static void purgeOldEntries (struct SyncRootStruct * root) [static]
Definition at line 1477 of file SyncActions.c.
Referenced by SyncInterestArrived().
static int RemRootDeltas (struct SyncRootStruct * root, struct SyncRootDeltas * deltas) [static]
Definition at line 2367 of file SyncActions.c.
Referenced by SendDeltasReply().
static int reportExclude (struct SyncRootStruct * root, struct ccn_buf_decoder * d) [static]
Definition at line 364 of file SyncActions.c.
Referenced by SyncInterestArrived().
static void ReprocessHeldInterest (struct SyncRootStruct * root) [static]
Definition at line 2328 of file SyncActions.c.
Referenced by UpdateAction().
static struct SyncRootDeltas* scanDeltas (struct SyncRootStruct * root, struct SyncHashCacheEntry * ceR) [static, read]
Definition at line 2509 of file SyncActions.c.
Referenced by SyncInterestArrived().
static struct SyncHashInfoList* scanRemoteSeen (struct SyncRootStruct * root, struct SyncHashCacheEntry * ceR) [static, read]
Definition at line 2464 of file SyncActions.c.
Referenced by UpdateAction().
static int SendDeltasReply (struct SyncRootStruct * root, struct SyncRootDeltas * deltas) [static]
Definition at line 2395 of file SyncActions.c.
Referenced by SyncInterestArrived(), and UpdateAction().
static void setCovered (struct SyncHashCacheEntry * ce) [static]
Definition at line 336 of file SyncActions.c.
Referenced by doComparison(), ensureRemoteEntry(), isCovered(), newNodeCommon(), and noteHash().
static void setFence (struct SyncBaseStruct * base) [static]
Definition at line 1888 of file SyncActions.c.
Referenced by HeartbeatAction().
static int showCacheEntry (struct SyncRootStruct * root, char * dst, int lim, char * prefix, struct SyncHashCacheEntry * ce) [static]
Definition at line 168 of file SyncActions.c.
Referenced by showCacheEntry1(), and showCacheEntry2().
static void showCacheEntry1 (struct SyncRootStruct * root, char * here, char * msg, struct SyncHashCacheEntry * ce) [static]
Definition at line 177 of file SyncActions.c.
Referenced by SyncInterestArrived(), SyncRemoteFetchResponse(), SyncSendRootAdviseInterest(), and SyncStartNodeFetch().
static void showCacheEntry2 (struct SyncRootStruct * root, char * here, char * msg, struct SyncHashCacheEntry * ce1, struct SyncHashCacheEntry * ce2) [static]
Definition at line 185 of file SyncActions.c.
Referenced by SendDeltasReply(), SyncInterestArrived(), SyncRootAdviseResponse(), and UpdateAction().
static int sync_notify_for_actions (struct sync_plumbing * sd, struct ccn_charbuf * name, int enum_index, uint64_t seq_num) [static]
Definition at line 3845 of file SyncActions.c.
static int sync_start_for_actions (struct sync_plumbing * sd, struct ccn_charbuf * state_buf) [static]
Definition at line 3824 of file SyncActions.c.
static void sync_stop_for_actions (struct sync_plumbing * sd, struct ccn_charbuf * state_buf) [static]
Definition at line 3924 of file SyncActions.c.
static struct SyncActionData* SyncFindAction (struct SyncRootStruct * root, enum SyncRegisterActionKind kind) [static, read]
Definition at line 2095 of file SyncActions.c.
Referenced by SyncSendRootAdviseInterest().
static int SyncHandleSlice (struct SyncBaseStruct * base, struct ccn_charbuf * name) [static]
Definition at line 2161 of file SyncActions.c.
Referenced by sync_notify_for_actions().
static enum ccn_upcall_res SyncInterestArrived (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info) [static]
Definition at line 2519 of file SyncActions.c.
Referenced by SyncRegisterInterest().
struct SyncBaseStruct* SyncNewBaseForActions (struct sync_plumbing * sd) [read]
construct a new base with methods at the SyncActions level
Definition at line 3940 of file SyncActions.c.
Referenced by r_init_create().
static int SyncRegisterInterest (struct SyncRootStruct * root, enum SyncRegisterActionKind kind) [static]
Definition at line 2812 of file SyncActions.c.
Referenced by SyncRegisterInterests().
static int SyncRegisterInterests (struct SyncRootStruct * root) [static]
Definition at line 2850 of file SyncActions.c.
Referenced by SyncHandleSlice().
static enum ccn_upcall_res SyncRemoteFetchResponse (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info) [static]
Definition at line 892 of file SyncActions.c.
Referenced by SyncStartContentFetch(), and SyncStartNodeFetch().
static enum ccn_upcall_res SyncRootAdviseResponse (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info) [static]
Definition at line 2904 of file SyncActions.c.
Referenced by SyncSendRootAdviseInterest().
static int SyncSendRootAdviseInterest (struct SyncRootStruct * root) [static]
Definition at line 3057 of file SyncActions.c.
Referenced by HeartbeatAction(), and UpdateAction().
static int SyncStartCompareAction (struct SyncRootStruct * root, struct ccn_charbuf * hashR) [static]
Definition at line 3740 of file SyncActions.c.
Referenced by HeartbeatAction(), and SyncRootAdviseResponse().
static int SyncStartContentFetch (struct SyncRootStruct * root, struct ccn_charbuf * name, struct SyncCompareData * comp) [static]
Definition at line 1516 of file SyncActions.c.
Referenced by CompareAction().
int SyncStartHeartbeat (struct SyncBaseStruct * base)
Definition at line 2052 of file SyncActions.c.
Referenced by sync_start_for_actions().
static int SyncStartNodeFetch (struct SyncRootStruct * root, struct SyncHashCacheEntry * ce, struct SyncCompareData * comp) [static]
Definition at line 1083 of file SyncActions.c.
Referenced by doComparison(), and doPreload().
static int SyncStartSliceEnum (struct SyncRootStruct * root) [static]
Definition at line 1858 of file SyncActions.c.
Referenced by HeartbeatAction(), and sync_notify_for_actions().
static int SyncTreeMergeNames (struct SyncTreeWorkerHead * head, struct SyncUpdateData * ud) [static]
Definition at line 3322 of file SyncActions.c.
Referenced by UpdateAction().
static int SyncUpdateRoot (struct SyncRootStruct * root) [static]
Definition at line 3693 of file SyncActions.c.
Referenced by HeartbeatAction().
static int TryNodeSplit (struct SyncUpdateData * ud) [static]
Definition at line 3204 of file SyncActions.c.
Referenced by AddUpdateName().
static int UpdateAction (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Definition at line 3470 of file SyncActions.c.
Referenced by SyncUpdateRoot().
Variable Documentation
int adviseNeedReset = 1 [static]
Definition at line 51 of file SyncActions.c.
Referenced by HeartbeatAction(), SyncInterestArrived(), SyncRegisterInterests(), and UpdateAction().
int cacheCleanBatch = 8 [static]
Definition at line 49 of file SyncActions.c.
Referenced by HeartbeatAction().
int cacheCleanDelta = 4 [static]
Definition at line 50 of file SyncActions.c.
Referenced by HeartbeatAction().
int cachePurgeTrigger = 60 [static]
Definition at line 48 of file SyncActions.c.
Referenced by purgeOldEntries().
int compareAssumeBad = 20 [static]
Definition at line 56 of file SyncActions.c.
Referenced by HeartbeatAction().
int fenceSeconds = 2 [static]
Definition at line 54 of file SyncActions.c.
Referenced by HeartbeatAction().
int hashSplitTrigger = 17 [static]
Definition at line 58 of file SyncActions.c.
Referenced by TryNodeSplit().
int namesYieldInc = 100 [static]
Definition at line 59 of file SyncActions.c.
Referenced by SyncTreeMergeNames(), and UpdateAction().
int namesYieldMicros = 20*1000 [static]
Definition at line 60 of file SyncActions.c.
Referenced by SyncTreeMergeNames(), and UpdateAction().
int nDeltasLimit = 4 [static]
Definition at line 47 of file SyncActions.c.
Referenced by SendDeltasReply().
int nodeSplitTrigger = 4000 [static]
Definition at line 57 of file SyncActions.c.
Referenced by AddUpdateName(), newNodeCommon(), nodeFromNodes(), and TryNodeSplit().
int shortDelayMicros = 1000 [static]
Definition at line 55 of file SyncActions.c.
Referenced by CompareAction(), HeartbeatAction(), kickCompare(), and UpdateAction().
int showHighLevel = 1 [static]
Definition at line 46 of file SyncActions.c.
Referenced by SendDeltasReply(), SyncInterestArrived(), SyncRemoteFetchResponse(), SyncRootAdviseResponse(), SyncSendRootAdviseInterest(), SyncStartNodeFetch(), and UpdateAction().
struct sync_plumbing_sync_methods syncActionMethods"Initial value:
 {
    &sync_start_for_actions,
    &sync_notify_for_actions,
    &sync_stop_for_actions
}
Definition at line 3933 of file SyncActions.c.
int updateNeedDelta = 6 [static]
Definition at line 53 of file SyncActions.c.
Referenced by HeartbeatAction().
int updateStallDelta = 15 [static]
Definition at line 52 of file SyncActions.c.
Referenced by HeartbeatAction().
int useCompExcl = 1 [static]
Definition at line 45 of file SyncActions.c.
Referenced by SyncInterestArrived().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.